[package]
name = "rcsharp"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "3"
members = ["rcsharp_lexer", "rcsharp_parser"]

[dependencies]
rcsharp_lexer = { path = "./rcsharp_lexer"}
rcsharp_parser = { path = "./rcsharp_parser"}
ordered_hash_map = "0.4.0"
regex = "1.11.2"
